# docker-compose.yml

services:
  fragments:
    init: true
    build: .
    depends_on:
      - localstack
      - dynamodb-local
    environment:
            # Our API will be running on http://localhost:8080
            - API_URL=http://localhost:8080
            # Use Cognito Auth (comment out for Basic Auth)
            # - HTPASSWD_FILE=tests/.htpasswd
            - AWS_COGNITO_POOL_ID=us-east-1_wqn2LAm1k
            - AWS_COGNITO_CLIENT_ID=5lsu19afmc8e56aprkprfk82d6

            # Use the LOG_LEVEL set in the host environment, or default to info
            - LOG_LEVEL=${LOG_LEVEL:-info}
            - AWS_REGION=us-east-1
            # AWS Credentials for LocalStack (test credentials)
            - AWS_ACCESS_KEY_ID=test
            - AWS_SECRET_ACCESS_KEY=test
            - AWS_SESSION_TOKEN=test
            # Use the LocalStack endpoint vs. AWS for S3 AWS SDK clients.
            # NOTE: we use Docker's internal network to the localstack container
            - AWS_S3_ENDPOINT_URL=http://localstack:4566
            # Use the DynamoDB local endpoint vs. AWS for DynamoDB AWS SDK clients.
            - AWS_DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
            # This S3 bucket and DynamoDB table need to get created first, see
            # local-aws-setup.sh. We'll default to 'fragments' as the name, unless
            # something else is defined in the env.
            - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-fragments}
            - AWS_DYNAMODB_TABLE_NAME=${AWS_DYNAMODB_TABLE_NAME:-fragments}
    
    ports:
      - '8080:8080'


  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    command: ['-jar', 'DynamoDBLocal.jar', '-inMemory']

  # LocalStack for S3, see https://docs.localstack.cloud/get-started/#docker-compose
  # Interact via awscli-local, see https://docs.localstack.cloud/integrations/aws-cli/#installation
  localstack:
    # https://hub.docker.com/r/localstack/localstack
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      # See https://docs.localstack.cloud/localstack/configuration/ and
      # https://hub.docker.com/r/localstack/localstack for config details.
      # We only want to run S3
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1